"""обновил свойство поля account

Revision ID: d77add1ac03c
Revises: db02c30e847a
Create Date: 2025-07-15 00:03:01.136837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77add1ac03c'
down_revision: Union[str, None] = 'db02c30e847a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'account',
               existing_type=sa.VARCHAR(length=70),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'account',
               existing_type=sa.VARCHAR(length=70),
               nullable=False)
    # ### end Alembic commands ###
