version: '3.8'

services:
  api:
    build:
      context: ./src
    container_name: fastapi_app
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    env_file:
      - ../infra/.env
    depends_on:
      - redis

#  worker:
#    build:
#      context: ./src
#    container_name: dramatiq_worker
#    command: >
#      dramatiq services.workers.dramatiq_app --processes 1 --threads 4
#    depends_on:
#      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
