from enum import StrEnum


class CityName(StrEnum):
    YEREVAN = 'ереван'
    ABOVYAN = 'абовян'
    ALAVERDI = 'алаверди'
    ANGEHAKOT = 'ангехакот'
    ARARAT = 'арарат'
    ARZNI = 'арзни'
    ARMAVIR = 'армавир'
    ARTASHAT = 'арташат'
    ARTIK = 'артик'
    AKHTALA = 'ахтала'
    ASHTARAK = 'аштарак'
    VANADZOR = 'ванадзор'
    VARDENIS = 'варденис'
    VAGHARSHAPAT = 'вагаршапат'
    GAVAR = 'гавар'
    GORIS = 'горис'
    GYUMRI = 'гюмри'
    DILIJAN = 'дилижан'
    IJEVAN = 'иджеван'
    KADJARAN = 'каджаран'
    KAPAN = 'капан'
    MARTUNI = 'мартуни'
    MEGHRI = 'мехри'
    RAZDAN = 'раздан'
    SEVAN = 'севан'
    SISIAN = 'сисиан'
    SPITAK = 'спитак'
    STEPANAVAN = 'степанаван'
    STEPANAKERT = 'степанакерт'
    TALIN = 'талин'
    TASHIR = 'ташир'
    CHARENTSAVAN = 'чаренцаван'
